substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port 
  send_wifi: "true"

esphome:
  name: haier-ac-ir-remote

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "haier-ac-ir-remote Fallback Hotspot"
    password: "0000"

web_server:
  port: 80

external_components:
  - source:
      type: git
      url: https://github.com/ResupinePuma/esphome-haier-ac-ir

sensor:
  # External temperature sensor from Home Assistant 
  - platform: homeassistant
    id: current_temperature
    entity_id: ${temperature_sensor}

climate:
  - platform: haier_acyrw02
    sensor_id: ${device_id}_current_temperature
    pin: 3 # Pin with IR led
    name: ${device_name}

  - platform: template
    id: ${device_id}_vertical_direction
    name: ${device_name} airflow vertical
    entity_category: config
    icon: mdi:arrow-expand-vertical
    optimistic: true
    restore_value: true
    initial_option: Auto 
    options:
      - Up
      - Center
      - Down
    on_value:
      then:
        - climate.haier_acyrw02.set_vertical_airflow:
           id: ${device_id}
           vertical_airflow: !lambda |-
             return esphome::haier_acyrw02::AirflowVerticalDirection(i);
